spring:
  application:
    name: order_service

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: orderservice
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true       # logs SQL queries in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081