server:
  port: 8082

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: paymentservice
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # options: none, validate, update, create, create-drop
    show-sql: true       # logs SQL queries in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


